### ISSUE TITLE
Build failing on master?

### ISSUE THREAD

**Issue by boldandbusted** [chef-cookbooks/postfix#118]
Howdy. Sorry for the leechy user question. The master branch has been failing to build (on FoodCritic via Travis) for 13 days. I'd love to make use of this cookbook, but is there a "successful" build I can use, perhaps that pre-dates this failing on? Thanks in advance!

Jesse

**Comment by voroniys** [comment]
The build is failing due to minor issues which has no influence on functionality. But if you really would like to have clean cookbook you can use my fork (pull request #114 ) - it has also some extra functionality.
