### ISSUE TITLE
Documentation error on readme: inet-interfaces

### ISSUE THREAD

**Issue by ricksebak** [chef-cookbooks/postfix#120]
The documentation on the readme describes how to create a role for a relayhost, and defines the override attributes as part of that role. One of those overrides lists "inet-interfaces" => "all". This option in postfix should use an underscore, not a dash.

Directly copy/pasting this role, without fixing the typo, results in:

grep interfaces /etc/postfix/main.cf 
inet-interfaces = all
inet_interfaces = loopback-only

**Comment by iennae** [comment]
Thanks for reporting this documentation issue. I've fixed the README.
